// <auto-generated />
using System;
using Agenda_Console.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Agenda_Console.Migrations
{
    [DbContext(typeof(AgendaContext))]
    [Migration("20210829012153_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Agenda_Console.Models.Atividades", b =>
                {
                    b.Property<int>("AtividadesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriasID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("AtividadesID");

                    b.HasIndex("CategoriasID");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("Agenda_Console.Models.Categorias", b =>
                {
                    b.Property<int>("CategoriasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriasID");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Agenda_Console.Models.Atividades", b =>
                {
                    b.HasOne("Agenda_Console.Models.Categorias", "Categorias")
                        .WithMany()
                        .HasForeignKey("CategoriasID");

                    b.Navigation("Categorias");
                });
#pragma warning restore 612, 618
        }
    }
}
